/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_LOGIN_electeur (void);
GtkWidget* create_GESTION (void);
GtkWidget* create_GESTION_LISTE (void);
GtkWidget* create_GESTION_USER (void);
GtkWidget* create_GESTION_OBSERV (void);
GtkWidget* create_GESTION_ELECTION (void);
GtkWidget* create_GESTION_BV (void);
GtkWidget* create_MODIF_LISTE (void);
GtkWidget* create_MODIF_USER (void);
GtkWidget* create_MODIF_OBSERV (void);
GtkWidget* create_MODIF_ELECTION (void);
GtkWidget* create_MODIFER_BV (void);
